import { useStoryStore } from '../store/useStoryStore';
import { StoryNode } from '../types/story';

export const executeCommand = (command: string): string => {
  const store = useStoryStore.getState();
  const lowerCmd = command.toLowerCase();

  // Command: "add node [Title] [type]"
  // Example: "add node The Ambush plot"
  if (lowerCmd.startsWith('add node')) {
    const parts = command.split(' ');
    // Assume last part is type if it matches known types, otherwise default to plot
    const knownTypes = ['plot', 'conflict', 'resolution', 'custom'];
    let type = 'plot';
    let titleParts = parts.slice(2);
    
    if (knownTypes.includes(parts[parts.length - 1])) {
        type = parts[parts.length - 1];
        titleParts = parts.slice(2, -1);
    }
    
    const title = titleParts.join(' ') || 'New Node';
    
    const newNode: StoryNode = {
      id: Date.now().toString(),
      type: 'storyNode',
      position: { x: Math.random() * 600 + 100, y: Math.random() * 400 + 100 },
      data: {
        title,
        outline: 'Generated by AI Agent based on your request.',
        content: '<p>Content generated by AI...</p>',
        type: type as any,
      },
    };
    store.addNode(newNode);
    return `Added node "${title}" (${type})`;
  }

  // Command: "link [sourceId] [targetId]"
  if (lowerCmd.startsWith('link')) {
    const parts = command.split(' ');
    const source = parts[1];
    const target = parts[2];
    
    if (source && target) {
        store.onConnect({ source, target, sourceHandle: null, targetHandle: null });
        return `Linked node ${source} to ${target}`;
    }
    return "Usage: link [sourceId] [targetId]";
  }
  
  // Command: "clear"
  if (lowerCmd === 'clear') {
      // We don't have a clear action, but we can implement it or just ignore
      return "Clear command not implemented yet";
  }

  return "Unknown command. Try 'add node [Title] [type]' or 'link [id] [id]'";
};
